name: Create Release

on:
  push:
    tags:
    - '*'

jobs:
  notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        name: Ilios ${{github.ref_name}}
        token: ${{ secrets.ZORGBORT_TOKEN }}
        generateReleaseNotes: true